# Generated by Django 4.1.3 on 2024-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='certificate',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
