# Generated by Django 5.0.6 on 2024-06-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='course',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
