# Generated by Django 4.1.3 on 2024-06-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='')),
                ('logo', models.ImageField(blank=True, upload_to='stack/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, verbose_name='icaromras@gmail.com')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='')),
                ('description', models.TextField(blank=True, null=True, verbose_name='')),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('avatar1', models.ImageField(blank=True, upload_to='about/')),
                ('avatar2', models.ImageField(blank=True, upload_to='about/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stacks', models.ManyToManyField(blank=True, to='about.stack')),
            ],
        ),
    ]
