# Generated by Django 4.1.3 on 2024-06-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='avatar1',
            field=models.ImageField(blank=True, upload_to='about/avatars'),
        ),
        migrations.AlterField(
            model_name='about',
            name='avatar2',
            field=models.ImageField(blank=True, upload_to='about/avatars'),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
