# Generated by Django 4.1.3 on 2024-07-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
