# Generated by Django 4.1.3 on 2024-07-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_category_thumbnail_alter_contributor_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
